/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

repositories {
  mavenCentral()
}

plugins {
  `java-library`
  // id("jtemplate.java-library-conventions")
}

dependencies {
    api(project(":list"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
}

tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        events("passed")
    }
}
